import 'src/styles/globals.css'
import Head from 'next/head';
import { useCounter } from "src/hooks/useCounter";
import { useInputArray } from "src/hooks/useInputArray";
import { useBgLightBlue } from "src/hooks/useBgLightBlue";
// import type { AppProps } from 'next/app'

function MyApp ({ Component, pageProps }) {
  const counter = useCounter();
  const inputArray = useInputArray();
  useBgLightBlue();

  return (
    <>
        <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} {...counter} {...inputArray} />
    </>
    );
}

// export default function App({ Component, pageProps }: AppProps) {
//   return <Component {...pageProps} />
// }

export default MyApp;